pipeline {
    agent { 
        label 'master'
    }
    options {
        // хранить логи последних 10 сборок и артефакты последних 10 сборок
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        // в графическом интерфейсе видеть временные отметки
        timestamps()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('WORKSPACE') {
        steps {
            sh "chmod +x -R ${env.WORKSPACE}"
        }
    }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
